### ISSUE TITLE
Eliminate pTemplates

### ISSUE THREAD

**Issue by spohnan** [cfn-stacks/cfn-base-vpc#2]
Needed so templates can reference other templates in the project but hopefully the token replacement mechanism could turn the version and group params into the correct string

```
rNatInstanceTemplate:
        Type: 'AWS::CloudFormation::Stack'
        Condition: cNeedNatInstance
        Properties:
            TemplateURL: !Sub '${pTemplates}/nat-instance.yaml'
```
